version: '3'

services:
  archrv-notification-bot:
    container_name: archrv-notification-bot
    build:
      context: .
    volumes:
      - ./db:/app/db
    env_file: .envfile
    restart: unless-stopped
